name: Main CI workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight run E2E tests
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  CYPRESS_CACHE_FOLDER: ./.cache/Cypress
  EMAIL_PRE: ${{ secrets.EMAIL_PRE }}
  EMAIL_POST: ${{ secrets.EMAIL_POST }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build and Install ⚙️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Download Config from S3 📥
        run: aws s3 sync s3://cypress-for-everything ./

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn and Node Modules 💾
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-v02-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v02-

      - name: Cache Cypress 💾
        id: cypress-cache
        uses: actions/cache@v2
        with:
          path: |
            .cache/Cypress
          key: ${{ runner.os }}-cypress-v02-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cypress-v02-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Refresh Gmail Access Token 🔄
        run: yarn refreshGmailToken

      - name: Upload Config to S3 📤
        run: aws s3 sync ./cypress/plugins s3://cypress-for-everything/cypress/plugins --include "*.json"

      - name: Install dependencies 🔧
        run: yarn install --frozen-lockfile --prefer-offline

      ## from https://github.com/vercel/next.js/blob/canary/.github/workflows/build_test_deploy.yml#L28
      - name: Cache all Repo for next jobs 💾
        uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  testsCypress:
    name: Test Cypress 🤖
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore Cache 💾
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run Cypress E2E tests 🏗️
        id: cypress-tests
        run: |
          yarn test

      - name: Merge all Reports
        if: always()
        run: |
          yarn merge

      - name: Publish Cypress E2E Report 📖
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress Tests Results 📖
          path: report.xml
          reporter: java-junit
          fail-on-error: "false"

      # - name: Upload Cypress Screenshots 📷
      #   uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots

      - name: Upload Cypress Videos 📹
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          fail-on-error: "false"
